name: Build and Test

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  run_build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check which modules changed
        id: changed_files
        uses: tj-actions/changed-files@v18.7

      - uses: actions/setup-node@v2
        with:
          node-version: 16.13
          cache: 'npm'
      - run: npm install --frozen-lockfile

      - name: Module inbox
        # if: contains(steps.changed_files.outputs.all_modified_files, 'inbox/')
        run: |
          npm run -w inbox build
          npm run -w inbox test

      - name: Module lottery
        # if: contains(steps.changed_files.outputs.all_modified_files, 'lottery/')
        run: |
          npm run -w lottery build
          npm run -w lottery test

      - name: Module lottery-web
        # if: contains(steps.changed_files.outputs.all_modified_files, 'lottery-web/')
        run: |
          npm run -w lottery-web build
          npm run -w lottery-web test --ci --verbose

      - name: Module kickstart
        # if: contains(steps.changed_files.outputs.all_modified_files, 'kickstart/')
        run: |
          npm run -w kickstart build:contract
          npm run -w kickstart test --ci --verbose
          npm run -w kickstart build
