name: Main

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  run_build:
    name: Run build and stuff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Verify Changed files
        id: changed_files
        uses: tj-actions/changed-files@v18.7
      - name: Run inbox
        if: contains(steps.changed_files.outputs.all_modified_files, 'inbox')
        run: echo "yarn inbox build && yarn inbox test"
      - name: Run kickstart
        if: contains(steps.changed_files.outputs.all_modified_files, 'kickstart')
        run: echo "yarn kickstart build && yarn kickstart test"
      - name: Run lottery
        if: contains(steps.changed_files.outputs.all_modified_files, 'lottery')
        run: echo "yarn lottery build && yarn lottery test"

  build_contract:
    name: Build Solidity Contract
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.13
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn inbox build
      - run: yarn inbox test
